name: flame_spine
description: Spine support for the Flame game engine.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.4.0
  flutter:
    sdk: flutter
  spine_core: ^0.3.4
  spine_flutter: ^0.1.3

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3
  flame_test: ^1.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
