name: flame_lottie_example
description: Flame sample for using lottie animations
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.4.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  lottie: ^1.4.3

dev_dependencies:
  flame_lint: ^0.1.3

