name: flame_spine_example
description: A testbed for flame_spine
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.4.0
  flame_spine:
  flutter:
    sdk: flutter


dev_dependencies:
  flame_lint: ^0.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/spineboy/
